import Head from "next/head";
import { Inter } from "@next/font/google";
import { Navbar } from "../components/navbar";
import { CallToAction } from "../components/calltoaction";
import { Footer } from "../components/footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Tailer UI Prebuilt Components || Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.ico" />
      </Head>
      <Navbar />

      <CallToAction />

      <Footer />
      
    </>
  );
}
